-- PostgreSQL schema for the existing software_testing database.
CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(120) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'user' CHECK (role IN ('user', 'admin')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_sessions (
    token_hash CHAR(64) PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS loan_applications (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    age INTEGER NOT NULL,
    monthly_income NUMERIC(12, 2) NOT NULL,
    monthly_debt NUMERIC(12, 2) NOT NULL,
    dti NUMERIC(5, 2) NOT NULL,
    credit_score INTEGER DEFAULT NULL,
    previous_loan_default VARCHAR(3) NOT NULL DEFAULT 'NO',
    historical_late_payments INTEGER NOT NULL DEFAULT 0,
    overdue_payments INTEGER NOT NULL DEFAULT 0,
    longest_previous_loan_months INTEGER DEFAULT NULL,
    credit_risk_score INTEGER DEFAULT NULL,
    credit_risk_category VARCHAR(20) DEFAULT NULL,
    loan_amount NUMERIC(12, 2) NOT NULL,
    decision VARCHAR(20) NOT NULL CHECK (decision IN ('APPROVED', 'REJECTED', 'MANUAL REVIEW')),
    reason TEXT NOT NULL,
    review_status VARCHAR(20) DEFAULT NULL,
    reviewed_at TIMESTAMPTZ DEFAULT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_notifications (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    application_id INTEGER REFERENCES loan_applications(id) ON DELETE CASCADE,
    title VARCHAR(160) NOT NULL,
    message TEXT NOT NULL,
    read_at TIMESTAMPTZ DEFAULT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS loan_rule_settings (
    setting_key VARCHAR(80) PRIMARY KEY,
    setting_value VARCHAR(80) NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
