/**
 * PostgreSQL connection and persistence module.
 */

const { Pool } = require('pg');
const bcrypt = require('bcryptjs');
require('dotenv').config();
const RULES_CONFIG = require('../config/rules.config');

const dbConfig = {
  host: process.env.DB_HOST || 'localhost',
  port: Number(process.env.DB_PORT) || 5432,
  user: process.env.DB_USER || 'postgres',
  password: process.env.DB_PASSWORD || '',
  database: process.env.DB_NAME || 'software_testing',
  max: 10,
  idleTimeoutMillis: 30000
};

let pool = null;
let isConnected = false;
let rulesConfiguration = null;

const applicationColumns = `
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  age INTEGER NOT NULL,
  monthly_income NUMERIC(12, 2) NOT NULL,
  monthly_debt NUMERIC(12, 2) NOT NULL,
  dti NUMERIC(5, 2) NOT NULL,
  credit_score INTEGER DEFAULT NULL,
  previous_loan_default VARCHAR(3) NOT NULL DEFAULT 'NO',
  historical_late_payments INTEGER NOT NULL DEFAULT 0,
  overdue_payments INTEGER NOT NULL DEFAULT 0,
  longest_previous_loan_months INTEGER DEFAULT NULL,
  credit_risk_score INTEGER DEFAULT NULL,
  credit_risk_category VARCHAR(20) DEFAULT NULL,
  loan_amount NUMERIC(12, 2) NOT NULL,
  decision VARCHAR(20) NOT NULL CHECK (decision IN ('APPROVED', 'REJECTED', 'MANUAL REVIEW')),
  reason TEXT NOT NULL,
  review_status VARCHAR(20) DEFAULT NULL,
  reviewed_at TIMESTAMPTZ DEFAULT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
`;

const selectApplicationColumns = `
  id, user_id, age, monthly_income, monthly_debt, dti, credit_score,
  previous_loan_default, historical_late_payments, overdue_payments,
  longest_previous_loan_months, credit_risk_score, credit_risk_category,
  loan_amount, decision, reason, review_status, reviewed_at, created_at,
  (SELECT full_name FROM users WHERE users.id = loan_applications.user_id) AS user_full_name,
  (SELECT email FROM users WHERE users.id = loan_applications.user_id) AS user_email
`;

async function createTables() {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS users (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      full_name VARCHAR(120) NOT NULL,
      email VARCHAR(255) NOT NULL UNIQUE,
      password_hash TEXT NOT NULL,
      role VARCHAR(20) NOT NULL DEFAULT 'user' CHECK (role IN ('user', 'admin')),
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
  `);
  await pool.query(`
    CREATE TABLE IF NOT EXISTS user_sessions (
      token_hash CHAR(64) PRIMARY KEY,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      expires_at TIMESTAMPTZ NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
  `);
  await pool.query(`CREATE TABLE IF NOT EXISTS loan_applications (${applicationColumns})`);
  await pool.query(`
    CREATE TABLE IF NOT EXISTS user_notifications (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      application_id INTEGER REFERENCES loan_applications(id) ON DELETE CASCADE,
      title VARCHAR(160) NOT NULL,
      message TEXT NOT NULL,
      read_at TIMESTAMPTZ DEFAULT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
  `);
  await pool.query(`
    CREATE TABLE IF NOT EXISTS loan_rule_settings (
      setting_key VARCHAR(80) PRIMARY KEY,
      setting_value VARCHAR(80) NOT NULL,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
  `);
  const migrations = [
    'ALTER TABLE loan_applications ADD COLUMN IF NOT EXISTS user_id INTEGER REFERENCES users(id) ON DELETE SET NULL',
    'ALTER TABLE loan_applications ADD COLUMN IF NOT EXISTS credit_score INTEGER DEFAULT NULL',
    "ALTER TABLE loan_applications ADD COLUMN IF NOT EXISTS previous_loan_default VARCHAR(3) NOT NULL DEFAULT 'NO'",
    'ALTER TABLE loan_applications ADD COLUMN IF NOT EXISTS historical_late_payments INTEGER NOT NULL DEFAULT 0',
    'ALTER TABLE loan_applications ADD COLUMN IF NOT EXISTS overdue_payments INTEGER NOT NULL DEFAULT 0',
    'ALTER TABLE loan_applications ADD COLUMN IF NOT EXISTS longest_previous_loan_months INTEGER DEFAULT NULL',
    'ALTER TABLE loan_applications ADD COLUMN IF NOT EXISTS credit_risk_score INTEGER DEFAULT NULL',
    "ALTER TABLE loan_applications ADD COLUMN IF NOT EXISTS credit_risk_category VARCHAR(20) DEFAULT NULL",
    'ALTER TABLE loan_applications ALTER COLUMN credit_risk_score DROP NOT NULL',
    'ALTER TABLE loan_applications ALTER COLUMN credit_risk_category DROP NOT NULL',
    'ALTER TABLE loan_applications ADD COLUMN IF NOT EXISTS review_status VARCHAR(20) DEFAULT NULL',
    'ALTER TABLE loan_applications ADD COLUMN IF NOT EXISTS reviewed_at TIMESTAMPTZ DEFAULT NULL',
    'ALTER TABLE loan_applications ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP'
  ];
  for (const migration of migrations) await pool.query(migration);
}

async function seedDemoUsers() {
  const demoUsers = [
    ['Demo User', 'user@loan.com', 'user123', 'user'],
    ['Loan Administrator', 'admin@loan.com', 'password123', 'admin']
  ];
  for (const [fullName, email, password, role] of demoUsers) {
    const passwordHash = await bcrypt.hash(password, 12);
    await pool.query(
      `INSERT INTO users (full_name, email, password_hash, role)
       VALUES ($1, $2, $3, $4) ON CONFLICT (email) DO NOTHING`,
      [fullName, email, passwordHash, role]
    );
  }
}

async function seedRuleSettings() {
  const configuration = RULES_CONFIG.getRulesConfiguration();
  for (const [key, value] of Object.entries(configuration)) {
    await pool.query(
      `INSERT INTO loan_rule_settings (setting_key, setting_value) VALUES ($1, $2)
       ON CONFLICT (setting_key) DO NOTHING`,
      [key, String(value)]
    );
  }
}

async function loadRulesConfigurationFromDatabase() {
  const { rows } = await pool.query('SELECT setting_key, setting_value FROM loan_rule_settings');
  if (rows.length > 0) {
    const updates = Object.fromEntries(rows.map(row => [
      row.setting_key,
      row.setting_value === 'true' || row.setting_value === 'false'
        ? row.setting_value === 'true'
        : Number(row.setting_value)
    ]));
    if (updates.dtiBorderlineEnabled !== undefined) updates.dtiBorderlineEnabled = Boolean(updates.dtiBorderlineEnabled);
    rulesConfiguration = RULES_CONFIG.updateRulesConfiguration(updates);
  } else {
    rulesConfiguration = RULES_CONFIG.getRulesConfiguration();
  }
  return rulesConfiguration;
}

async function initializeDatabase() {
  if (isConnected && pool) return true;
  pool = new Pool(dbConfig);
  try {
    await pool.query('SELECT 1');
    await createTables();
    await seedDemoUsers();
    await seedRuleSettings();
    isConnected = true;
    await loadRulesConfigurationFromDatabase();
    console.log(`[Database] Successfully connected to PostgreSQL database: ${dbConfig.database}`);
    return true;
  } catch (error) {
    isConnected = false;
    await pool.end().catch(() => {});
    pool = null;
    throw new Error(`PostgreSQL connection or initialization failed: ${error.message}`);
  }
}

async function ensureDatabaseReady() {
  if (!isConnected || !pool) await initializeDatabase();
}

/**
 * Saves a loan application and decision to the database.
 * 
 * @param {Object} record
 * @returns {Promise<Object>} Inserted record with generated ID and timestamp
 */
async function saveApplicationRecord(record) {
  await ensureDatabaseReady();
  const {
    age, monthlyIncome, monthlyDebt, dti, previousLoanDefault, historicalLatePayments,
    overduePayments, longestPreviousLoanRepaymentMonths, creditRiskScore,
    creditRiskCategory, loanAmount, decision, reason, userId
  } = record;

  const { rows } = await pool.query(
    `INSERT INTO loan_applications
      (user_id, age, monthly_income, monthly_debt, dti, previous_loan_default,
       historical_late_payments, overdue_payments, longest_previous_loan_months,
       credit_risk_score, credit_risk_category, loan_amount, decision, reason, review_status)
    VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
     RETURNING ${selectApplicationColumns}`,
    [userId || null, age, monthlyIncome, monthlyDebt, dti, previousLoanDefault, historicalLatePayments,
      overduePayments, longestPreviousLoanRepaymentMonths, creditRiskScore,
      creditRiskCategory, loanAmount, decision, reason, record.review_status || null]
  );
  return { ...rows[0], storage: 'postgresql' };
}

async function createUser({ fullName, email, password }) {
  await ensureDatabaseReady();
  const normalizedEmail = email.trim().toLowerCase();
  const passwordHash = await bcrypt.hash(password, 12);
  const { rows } = await pool.query(
    `INSERT INTO users (full_name, email, password_hash)
     VALUES ($1, $2, $3)
     RETURNING id, full_name, email, role, created_at`,
    [fullName.trim(), normalizedEmail, passwordHash]
  );
  return rows[0];
}

async function authenticateUser(email, password) {
  await ensureDatabaseReady();
  const { rows } = await pool.query(
    'SELECT id, full_name, email, password_hash, role, created_at FROM users WHERE email = $1',
    [email.trim().toLowerCase()]
  );
  const user = rows[0];
  if (!user || !(await bcrypt.compare(password, user.password_hash))) return null;
  delete user.password_hash;
  return user;
}

async function createSession(userId) {
  await ensureDatabaseReady();
  const token = require('crypto').randomBytes(32).toString('hex');
  const tokenHash = require('crypto').createHash('sha256').update(token).digest('hex');
  await pool.query(
    `INSERT INTO user_sessions (token_hash, user_id, expires_at)
     VALUES ($1, $2, CURRENT_TIMESTAMP + INTERVAL '7 days')`,
    [tokenHash, userId]
  );
  return token;
}

async function findUserBySession(token) {
  if (!token) return null;
  await ensureDatabaseReady();
  const tokenHash = require('crypto').createHash('sha256').update(token).digest('hex');
  const { rows } = await pool.query(
    `SELECT u.id, u.full_name, u.email, u.role, u.created_at
     FROM user_sessions s JOIN users u ON u.id = s.user_id
     WHERE s.token_hash = $1 AND s.expires_at > CURRENT_TIMESTAMP`,
    [tokenHash]
  );
  return rows[0] || null;
}

/**
 * Fetches all past loan applications ordered from newest to oldest.
 * 
 * @param {number} [limit=50]
 * @returns {Promise<Array>}
 */
async function fetchApplicationHistory(limit = 50) {
  await ensureDatabaseReady();
  const { rows } = await pool.query(
    `SELECT ${selectApplicationColumns} FROM loan_applications ORDER BY id DESC LIMIT $1`,
    [limit]
  );
  return rows;
}

async function loadRulesConfiguration() {
  await ensureDatabaseReady();
  return loadRulesConfigurationFromDatabase();
}

async function saveRulesConfiguration(configuration) {
  await ensureDatabaseReady();
  rulesConfiguration = RULES_CONFIG.updateRulesConfiguration(configuration);
  for (const [key, value] of Object.entries(rulesConfiguration)) {
    await pool.query(
      `INSERT INTO loan_rule_settings (setting_key, setting_value, updated_at)
       VALUES ($1, $2, CURRENT_TIMESTAMP)
       ON CONFLICT (setting_key) DO UPDATE SET
         setting_value = EXCLUDED.setting_value, updated_at = CURRENT_TIMESTAMP`,
      [key, String(value)]
    );
  }
  return rulesConfiguration;
}

/**
 * Fetches all pending manual review applications.
 * @returns {Promise<Array>}
 */
async function fetchPendingManualReviews() {
  await ensureDatabaseReady();
  const { rows } = await pool.query(
    `SELECT ${selectApplicationColumns} FROM loan_applications
     WHERE decision = 'MANUAL REVIEW' AND review_status = 'PENDING' ORDER BY id DESC`
  );
  return rows;
}

/**
 * Fetches a single application by ID.
 * @param {number|string} id
 * @returns {Promise<Object|null>}
 */
async function fetchApplicationById(id) {
  await ensureDatabaseReady();
  const { rows } = await pool.query(
    `SELECT ${selectApplicationColumns} FROM loan_applications WHERE id = $1`,
    [Number(id)]
  );
  return rows[0] || null;
}

// Closes the database pool (useful for clean test teardowns).
async function closeDatabase() {
  if (pool) {
    await pool.end();
    pool = null;
    isConnected = false;
  }
}

// Retrieves pool health status.
function getPoolStatus() {
  return {
    isConnected,
    poolExists: !!pool
  };
}

/**
 * Updates the review status for a given application ID.
 * Only applications with decision = 'MANUAL REVIEW' and review_status = 'PENDING'
 * can be reviewed.
 *
 * @param {number|string} id
 * @param {string} status - 'APPROVED' or 'REJECTED'
 * @returns {Promise<Object>}
 */
async function updateReviewStatus(id, status) {
  if (!['APPROVED', 'REJECTED'].includes(status)) {
    throw new Error('Invalid review status. Must be APPROVED or REJECTED.');
  }

  await ensureDatabaseReady();
  const record = await fetchApplicationById(id);
  if (!record) throw new Error('Record not found');
  if (record.decision !== 'MANUAL REVIEW' || record.review_status !== 'PENDING') {
    throw new Error('This application has already been reviewed or is not eligible for manual review.');
  }
  await pool.query(
    `UPDATE loan_applications
     SET decision = $1, review_status = 'COMPLETED', reviewed_at = CURRENT_TIMESTAMP
     WHERE id = $2 AND review_status = 'PENDING'`,
    [status, Number(id)]
  );
  let notification = null;
  if (status === 'APPROVED' && record.user_id) {
    const result = await pool.query(
      `INSERT INTO user_notifications (user_id, application_id, title, message)
       VALUES ($1, $2, $3, $4)
       RETURNING id, title, message, read_at, created_at`,
      [
        record.user_id,
        Number(id),
        'Loan approved',
        'Congratulations! Your loan application has been approved by a loan officer.'
      ]
    );
    notification = result.rows[0];
  }
  return { id: Number(id), decision: status, review_status: 'COMPLETED', notification };
}

async function fetchApplicationNotification(id, userId = null) {
  await ensureDatabaseReady();
  const params = [Number(id)];
  let userClause = '';
  if (userId) {
    params.push(userId);
    userClause = ' AND user_id = $2';
  }
  const { rows } = await pool.query(
    `SELECT id, title, message, read_at, created_at
     FROM user_notifications WHERE application_id = $1${userClause}
     ORDER BY id DESC LIMIT 1`,
    params
  );
  return rows[0] || null;
}

async function clearDatabase() {
  await ensureDatabaseReady();
  await pool.query('TRUNCATE TABLE user_notifications, loan_applications RESTART IDENTITY');
}

module.exports = {
  initializeDatabase,
  createUser,
  authenticateUser,
  createSession,
  findUserBySession,
  saveApplicationRecord,
  fetchApplicationHistory,
  fetchPendingManualReviews,
  fetchApplicationById,
  closeDatabase,
  getPoolStatus,
  updateReviewStatus,
  fetchApplicationNotification,
  isDatabaseConnected: () => isConnected,
  clearDatabase,
  loadRulesConfiguration,
  saveRulesConfiguration
};
